#server:
#  port: 8999
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888/
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ${SPRING_CLOUD_GATEWAY_ROUTES_0_ID:users-service}
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI:http://localhost:9001/}
          predicates:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0:Path=/auth/**}
          filters:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0:AuthFilter}
        - id: health-services
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI:http://localhost:9002/}
          predicates:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES:Path=/health/**}
          filters:
            - AuthFilter
        - id: users-healths
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_2_URI:http://localhost:9003/}
          predicates:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES:Path=/users-health/**}
          filters:
            - AuthFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN-SERVER:localhost}:9411/api/v2/spans