server:
  port: 8999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: ${SPRING_CLOUD_GATEWAY_ROUTES_0_ID:users-service}
#          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI:http://localhost:9001/}
#          predicates:
#            - ${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0:Path=/auth/**}
#          filters:
#            -  ${SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0:AuthFilter}
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"